// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Serv3_AreaStatusControl.proto

package grpc.service3;

public final class AreaStatusControlImpl {
  private AreaStatusControlImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PollutionWatch_riverDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PollutionWatch_riverDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PollutionWatch_riverDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PollutionWatch_riverDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PollutionWatch_waterStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PollutionWatch_waterStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PollutionWatch_waterStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PollutionWatch_waterStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PollutionWatch_neighborhoodStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PollutionWatch_neighborhoodStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PollutionWatch_neighborhoodStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PollutionWatch_neighborhoodStatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035Serv3_AreaStatusControl.proto\022\016Polluti" +
      "onWatch\"(\n\020riverDataRequest\022\024\n\014riverData" +
      "Req\030\001 \001(\t\")\n\021riverDataResponse\022\024\n\014riverD" +
      "ataRes\030\001 \001(\t\",\n\022waterStatusRequest\022\026\n\016wa" +
      "terStatusReq\030\001 \001(\t\"-\n\023waterStatusRespons" +
      "e\022\026\n\016waterStatusRes\030\001 \001(\t\":\n\031neighborhoo" +
      "dStatusRequest\022\035\n\025neighborhoodStatusReq\030" +
      "\001 \001(\t\";\n\032neighborhoodStatusResponse\022\035\n\025n" +
      "eighborhoodStatusRes\030\001 \001(\t2\273\002\n\021AreaStatu" +
      "sControl\022X\n\rriverHistoric\022 .PollutionWat" +
      "ch.riverDataRequest\032!.PollutionWatch.riv" +
      "erDataResponse\"\0000\001\022Z\n\tBidiRiver\022\".Pollut" +
      "ionWatch.waterStatusRequest\032#.PollutionW" +
      "atch.waterStatusResponse\"\000(\0010\001\022p\n\021BidiNe" +
      "ighbourhood\022).PollutionWatch.neighborhoo" +
      "dStatusRequest\032*.PollutionWatch.neighbor" +
      "hoodStatusResponse\"\000(\0010\001B(\n\rgrpc.service" +
      "3B\025AreaStatusControlImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PollutionWatch_riverDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PollutionWatch_riverDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PollutionWatch_riverDataRequest_descriptor,
        new java.lang.String[] { "RiverDataReq", });
    internal_static_PollutionWatch_riverDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PollutionWatch_riverDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PollutionWatch_riverDataResponse_descriptor,
        new java.lang.String[] { "RiverDataRes", });
    internal_static_PollutionWatch_waterStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PollutionWatch_waterStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PollutionWatch_waterStatusRequest_descriptor,
        new java.lang.String[] { "WaterStatusReq", });
    internal_static_PollutionWatch_waterStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PollutionWatch_waterStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PollutionWatch_waterStatusResponse_descriptor,
        new java.lang.String[] { "WaterStatusRes", });
    internal_static_PollutionWatch_neighborhoodStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_PollutionWatch_neighborhoodStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PollutionWatch_neighborhoodStatusRequest_descriptor,
        new java.lang.String[] { "NeighborhoodStatusReq", });
    internal_static_PollutionWatch_neighborhoodStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_PollutionWatch_neighborhoodStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PollutionWatch_neighborhoodStatusResponse_descriptor,
        new java.lang.String[] { "NeighborhoodStatusRes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
