// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Serv1_RiverWaterControl.proto

package grpc.service1;

public final class RiverWaterControlImpl {
  private RiverWaterControlImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PollutionWatch_testRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PollutionWatch_testRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PollutionWatch_testResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PollutionWatch_testResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PollutionWatch_deepTestRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PollutionWatch_deepTestRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PollutionWatch_deepTestResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PollutionWatch_deepTestResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PollutionWatch_riverDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PollutionWatch_riverDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PollutionWatch_riverDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PollutionWatch_riverDataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035Serv1_RiverWaterControl.proto\022\016Polluti" +
      "onWatch\"\036\n\013testRequest\022\017\n\007testReq\030\001 \001(\002\"" +
      "\037\n\014testResponse\022\017\n\007testRes\030\001 \001(\t\"Y\n\017deep" +
      "TestRequest\022\026\n\016deepTestReqOxy\030\001 \001(\002\022\027\n\017d" +
      "eepTestReqTemp\030\002 \001(\002\022\025\n\rdeepTestReqPh\030\003 " +
      "\001(\002\"\'\n\020deepTestResponse\022\023\n\013deepTestRes\030\001" +
      " \001(\t\"s\n\020riverDataRequest\022\024\n\014riverDataReq" +
      "\030\001 \001(\t\022\027\n\017riverDataReqOxy\030\002 \001(\002\022\030\n\020river" +
      "DataReqTemp\030\003 \001(\002\022\026\n\016riverDataReqPh\030\004 \001(" +
      "\002\")\n\021riverDataResponse\022\024\n\014riverDataRes\030\001" +
      " \001(\t2\215\002\n\021RiverWaterControl\022J\n\013oxigenLeve" +
      "l\022\033.PollutionWatch.testRequest\032\034.Polluti" +
      "onWatch.testResponse\"\000\022S\n\nmanyValues\022\037.P" +
      "ollutionWatch.deepTestRequest\032 .Pollutio" +
      "nWatch.deepTestResponse\"\000(\001\022W\n\014manyReadi" +
      "ngs\022 .PollutionWatch.riverDataRequest\032!." +
      "PollutionWatch.riverDataResponse\"\000(\001B(\n\r" +
      "grpc.service1B\025RiverWaterControlImplP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PollutionWatch_testRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PollutionWatch_testRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PollutionWatch_testRequest_descriptor,
        new java.lang.String[] { "TestReq", });
    internal_static_PollutionWatch_testResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PollutionWatch_testResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PollutionWatch_testResponse_descriptor,
        new java.lang.String[] { "TestRes", });
    internal_static_PollutionWatch_deepTestRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PollutionWatch_deepTestRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PollutionWatch_deepTestRequest_descriptor,
        new java.lang.String[] { "DeepTestReqOxy", "DeepTestReqTemp", "DeepTestReqPh", });
    internal_static_PollutionWatch_deepTestResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PollutionWatch_deepTestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PollutionWatch_deepTestResponse_descriptor,
        new java.lang.String[] { "DeepTestRes", });
    internal_static_PollutionWatch_riverDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_PollutionWatch_riverDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PollutionWatch_riverDataRequest_descriptor,
        new java.lang.String[] { "RiverDataReq", "RiverDataReqOxy", "RiverDataReqTemp", "RiverDataReqPh", });
    internal_static_PollutionWatch_riverDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_PollutionWatch_riverDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PollutionWatch_riverDataResponse_descriptor,
        new java.lang.String[] { "RiverDataRes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
