// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Serv2_AirQualityCheck.proto

package grpc.service2;

public interface airDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PollutionWatch.airDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float airDataReqMon = 1;</code>
   */
  float getAirDataReqMon();

  /**
   * <code>float airDataReqOz = 2;</code>
   */
  float getAirDataReqOz();
}
