// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Serv2_AirQualityCheck.proto

package grpc.service2;

public interface airOxygenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PollutionWatch.airOxygenResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float airOxygenResPer = 1;</code>
   */
  float getAirOxygenResPer();

  /**
   * <code>string airOxygenResHea = 2;</code>
   */
  java.lang.String getAirOxygenResHea();
  /**
   * <code>string airOxygenResHea = 2;</code>
   */
  com.google.protobuf.ByteString
      getAirOxygenResHeaBytes();
}
