// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Serv2_AirQualityCheck.proto

package grpc.service2;

public final class AirQualityCheckImpl {
  private AirQualityCheckImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PollutionWatch_statusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PollutionWatch_statusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PollutionWatch_statusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PollutionWatch_statusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PollutionWatch_airOxygenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PollutionWatch_airOxygenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PollutionWatch_airOxygenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PollutionWatch_airOxygenResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PollutionWatch_airDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PollutionWatch_airDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PollutionWatch_airDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PollutionWatch_airDataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033Serv2_AirQualityCheck.proto\022\016Pollution" +
      "Watch\"\"\n\rstatusRequest\022\021\n\tstatusReq\030\001 \001(" +
      "\t\"#\n\016statusResponse\022\021\n\tstatusRes\030\001 \001(\t\"D" +
      "\n\020airOxygenRequest\022\027\n\017airOxygenReqBef\030\001 " +
      "\001(\002\022\027\n\017airOxygenReqAft\030\002 \001(\002\"E\n\021airOxyge" +
      "nResponse\022\027\n\017airOxygenResPer\030\001 \001(\002\022\027\n\017ai" +
      "rOxygenResHea\030\002 \001(\t\"=\n\016airDataRequest\022\025\n" +
      "\rairDataReqMon\030\001 \001(\002\022\024\n\014airDataReqOz\030\002 \001" +
      "(\002\"%\n\017airDataResponse\022\022\n\nairDataRes\030\001 \001(" +
      "\t2\230\002\n\017AirQualityCheck\022T\n\021neighbourhoodNa" +
      "me\022\035.PollutionWatch.statusRequest\032\036.Poll" +
      "utionWatch.statusResponse\"\000\022W\n\nBidiOxyge" +
      "n\022 .PollutionWatch.airOxygenRequest\032!.Po" +
      "llutionWatch.airOxygenResponse\"\000(\0010\001\022V\n\017" +
      "manyAirReadings\022\036.PollutionWatch.airData" +
      "Request\032\037.PollutionWatch.airDataResponse" +
      "\"\000(\001B&\n\rgrpc.service2B\023AirQualityCheckIm" +
      "plP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PollutionWatch_statusRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PollutionWatch_statusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PollutionWatch_statusRequest_descriptor,
        new java.lang.String[] { "StatusReq", });
    internal_static_PollutionWatch_statusResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PollutionWatch_statusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PollutionWatch_statusResponse_descriptor,
        new java.lang.String[] { "StatusRes", });
    internal_static_PollutionWatch_airOxygenRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PollutionWatch_airOxygenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PollutionWatch_airOxygenRequest_descriptor,
        new java.lang.String[] { "AirOxygenReqBef", "AirOxygenReqAft", });
    internal_static_PollutionWatch_airOxygenResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PollutionWatch_airOxygenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PollutionWatch_airOxygenResponse_descriptor,
        new java.lang.String[] { "AirOxygenResPer", "AirOxygenResHea", });
    internal_static_PollutionWatch_airDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_PollutionWatch_airDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PollutionWatch_airDataRequest_descriptor,
        new java.lang.String[] { "AirDataReqMon", "AirDataReqOz", });
    internal_static_PollutionWatch_airDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_PollutionWatch_airDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PollutionWatch_airDataResponse_descriptor,
        new java.lang.String[] { "AirDataRes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
