// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Serv2_AirQualityCheck.proto

package grpc.service2;

public interface statusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PollutionWatch.statusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string statusRes = 1;</code>
   */
  java.lang.String getStatusRes();
  /**
   * <code>string statusRes = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusResBytes();
}
