// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Serv2_AirQualityCheck.proto

package grpc.service2;

public interface statusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PollutionWatch.statusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string statusReq = 1;</code>
   */
  java.lang.String getStatusReq();
  /**
   * <code>string statusReq = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusReqBytes();
}
