// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Serv1_RiverWaterControl.proto

package grpc.service1;

public interface deepTestResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PollutionWatch.deepTestResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string deepTestRes = 1;</code>
   */
  java.lang.String getDeepTestRes();
  /**
   * <code>string deepTestRes = 1;</code>
   */
  com.google.protobuf.ByteString
      getDeepTestResBytes();
}
