// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Serv1_RiverWaterControl.proto

package grpc.service1;

public interface deepTestRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PollutionWatch.deepTestRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float deepTestReqOxy = 1;</code>
   */
  float getDeepTestReqOxy();

  /**
   * <code>float deepTestReqTemp = 2;</code>
   */
  float getDeepTestReqTemp();

  /**
   * <code>float deepTestReqPh = 3;</code>
   */
  float getDeepTestReqPh();
}
