// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Serv1_RiverWaterControl.proto

package grpc.service1;

public interface testResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PollutionWatch.testResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string testRes = 1;</code>
   */
  java.lang.String getTestRes();
  /**
   * <code>string testRes = 1;</code>
   */
  com.google.protobuf.ByteString
      getTestResBytes();
}
