// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Serv1_RiverWaterControl.proto

package grpc.service1;

public interface testRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PollutionWatch.testRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float testReq = 1;</code>
   */
  float getTestReq();
}
