// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Serv2_AirQualityCheck.proto

package grpc.service2;

public interface airDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PollutionWatch.airDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string airDataRes = 1;</code>
   */
  java.lang.String getAirDataRes();
  /**
   * <code>string airDataRes = 1;</code>
   */
  com.google.protobuf.ByteString
      getAirDataResBytes();
}
