// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Serv2_AirQualityCheck.proto

package grpc.service2;

public interface airOxygenRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PollutionWatch.airOxygenRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float airOxygenReqBef = 1;</code>
   */
  float getAirOxygenReqBef();

  /**
   * <code>float airOxygenReqAft = 2;</code>
   */
  float getAirOxygenReqAft();
}
