// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Serv3_AreaStatusControl.proto

package grpc.service3;

/**
 * <pre>
 * Define the messages for BidiNeighbourhood method
 *(Bidirectional) The client sends 2 neighborhood names
 * The server will answer with data from this two neighborhood.
 * </pre>
 *
 * Protobuf type {@code PollutionWatch.neighborhoodStatusRequest}
 */
public  final class neighborhoodStatusRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PollutionWatch.neighborhoodStatusRequest)
    neighborhoodStatusRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use neighborhoodStatusRequest.newBuilder() to construct.
  private neighborhoodStatusRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private neighborhoodStatusRequest() {
    neighborhoodStatusReq_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private neighborhoodStatusRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            neighborhoodStatusReq_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.service3.AreaStatusControlImpl.internal_static_PollutionWatch_neighborhoodStatusRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.service3.AreaStatusControlImpl.internal_static_PollutionWatch_neighborhoodStatusRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.service3.neighborhoodStatusRequest.class, grpc.service3.neighborhoodStatusRequest.Builder.class);
  }

  public static final int NEIGHBORHOODSTATUSREQ_FIELD_NUMBER = 1;
  private volatile java.lang.Object neighborhoodStatusReq_;
  /**
   * <code>string neighborhoodStatusReq = 1;</code>
   */
  public java.lang.String getNeighborhoodStatusReq() {
    java.lang.Object ref = neighborhoodStatusReq_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      neighborhoodStatusReq_ = s;
      return s;
    }
  }
  /**
   * <code>string neighborhoodStatusReq = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNeighborhoodStatusReqBytes() {
    java.lang.Object ref = neighborhoodStatusReq_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      neighborhoodStatusReq_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNeighborhoodStatusReqBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, neighborhoodStatusReq_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNeighborhoodStatusReqBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, neighborhoodStatusReq_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.service3.neighborhoodStatusRequest)) {
      return super.equals(obj);
    }
    grpc.service3.neighborhoodStatusRequest other = (grpc.service3.neighborhoodStatusRequest) obj;

    boolean result = true;
    result = result && getNeighborhoodStatusReq()
        .equals(other.getNeighborhoodStatusReq());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NEIGHBORHOODSTATUSREQ_FIELD_NUMBER;
    hash = (53 * hash) + getNeighborhoodStatusReq().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.service3.neighborhoodStatusRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.service3.neighborhoodStatusRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.service3.neighborhoodStatusRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.service3.neighborhoodStatusRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.service3.neighborhoodStatusRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.service3.neighborhoodStatusRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.service3.neighborhoodStatusRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.service3.neighborhoodStatusRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.service3.neighborhoodStatusRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.service3.neighborhoodStatusRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.service3.neighborhoodStatusRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.service3.neighborhoodStatusRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.service3.neighborhoodStatusRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Define the messages for BidiNeighbourhood method
   *(Bidirectional) The client sends 2 neighborhood names
   * The server will answer with data from this two neighborhood.
   * </pre>
   *
   * Protobuf type {@code PollutionWatch.neighborhoodStatusRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PollutionWatch.neighborhoodStatusRequest)
      grpc.service3.neighborhoodStatusRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.service3.AreaStatusControlImpl.internal_static_PollutionWatch_neighborhoodStatusRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.service3.AreaStatusControlImpl.internal_static_PollutionWatch_neighborhoodStatusRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.service3.neighborhoodStatusRequest.class, grpc.service3.neighborhoodStatusRequest.Builder.class);
    }

    // Construct using grpc.service3.neighborhoodStatusRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      neighborhoodStatusReq_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.service3.AreaStatusControlImpl.internal_static_PollutionWatch_neighborhoodStatusRequest_descriptor;
    }

    @java.lang.Override
    public grpc.service3.neighborhoodStatusRequest getDefaultInstanceForType() {
      return grpc.service3.neighborhoodStatusRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.service3.neighborhoodStatusRequest build() {
      grpc.service3.neighborhoodStatusRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.service3.neighborhoodStatusRequest buildPartial() {
      grpc.service3.neighborhoodStatusRequest result = new grpc.service3.neighborhoodStatusRequest(this);
      result.neighborhoodStatusReq_ = neighborhoodStatusReq_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.service3.neighborhoodStatusRequest) {
        return mergeFrom((grpc.service3.neighborhoodStatusRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.service3.neighborhoodStatusRequest other) {
      if (other == grpc.service3.neighborhoodStatusRequest.getDefaultInstance()) return this;
      if (!other.getNeighborhoodStatusReq().isEmpty()) {
        neighborhoodStatusReq_ = other.neighborhoodStatusReq_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.service3.neighborhoodStatusRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.service3.neighborhoodStatusRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object neighborhoodStatusReq_ = "";
    /**
     * <code>string neighborhoodStatusReq = 1;</code>
     */
    public java.lang.String getNeighborhoodStatusReq() {
      java.lang.Object ref = neighborhoodStatusReq_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        neighborhoodStatusReq_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string neighborhoodStatusReq = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNeighborhoodStatusReqBytes() {
      java.lang.Object ref = neighborhoodStatusReq_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        neighborhoodStatusReq_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string neighborhoodStatusReq = 1;</code>
     */
    public Builder setNeighborhoodStatusReq(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      neighborhoodStatusReq_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string neighborhoodStatusReq = 1;</code>
     */
    public Builder clearNeighborhoodStatusReq() {
      
      neighborhoodStatusReq_ = getDefaultInstance().getNeighborhoodStatusReq();
      onChanged();
      return this;
    }
    /**
     * <code>string neighborhoodStatusReq = 1;</code>
     */
    public Builder setNeighborhoodStatusReqBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      neighborhoodStatusReq_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PollutionWatch.neighborhoodStatusRequest)
  }

  // @@protoc_insertion_point(class_scope:PollutionWatch.neighborhoodStatusRequest)
  private static final grpc.service3.neighborhoodStatusRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.service3.neighborhoodStatusRequest();
  }

  public static grpc.service3.neighborhoodStatusRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<neighborhoodStatusRequest>
      PARSER = new com.google.protobuf.AbstractParser<neighborhoodStatusRequest>() {
    @java.lang.Override
    public neighborhoodStatusRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new neighborhoodStatusRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<neighborhoodStatusRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<neighborhoodStatusRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.service3.neighborhoodStatusRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

