// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Serv3_AreaStatusControl.proto

package grpc.service3;

public interface neighborhoodStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PollutionWatch.neighborhoodStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string neighborhoodStatusRes = 1;</code>
   */
  java.lang.String getNeighborhoodStatusRes();
  /**
   * <code>string neighborhoodStatusRes = 1;</code>
   */
  com.google.protobuf.ByteString
      getNeighborhoodStatusResBytes();
}
