// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Serv3_AreaStatusControl.proto

package grpc.service3;

public interface neighborhoodStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PollutionWatch.neighborhoodStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string neighborhoodStatusReq = 1;</code>
   */
  java.lang.String getNeighborhoodStatusReq();
  /**
   * <code>string neighborhoodStatusReq = 1;</code>
   */
  com.google.protobuf.ByteString
      getNeighborhoodStatusReqBytes();
}
