// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Serv3_AreaStatusControl.proto

package grpc.service3;

public interface riverDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PollutionWatch.riverDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string riverDataReq = 1;</code>
   */
  java.lang.String getRiverDataReq();
  /**
   * <code>string riverDataReq = 1;</code>
   */
  com.google.protobuf.ByteString
      getRiverDataReqBytes();
}
