// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Serv3_AreaStatusControl.proto

package grpc.service3;

public interface riverDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PollutionWatch.riverDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string riverDataRes = 1;</code>
   */
  java.lang.String getRiverDataRes();
  /**
   * <code>string riverDataRes = 1;</code>
   */
  com.google.protobuf.ByteString
      getRiverDataResBytes();
}
