// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Serv3_AreaStatusControl.proto

package grpc.service3;

public interface waterStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PollutionWatch.waterStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string waterStatusReq = 1;</code>
   */
  java.lang.String getWaterStatusReq();
  /**
   * <code>string waterStatusReq = 1;</code>
   */
  com.google.protobuf.ByteString
      getWaterStatusReqBytes();
}
