// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Serv3_AreaStatusControl.proto

package grpc.service3;

public interface waterStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PollutionWatch.waterStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string waterStatusRes = 1;</code>
   */
  java.lang.String getWaterStatusRes();
  /**
   * <code>string waterStatusRes = 1;</code>
   */
  com.google.protobuf.ByteString
      getWaterStatusResBytes();
}
